<?php
/**
 * Copyright 2020 LABOR.digital
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Last modified: 2020.07.16 at 18:48
 */

declare(strict_types=1);
/**
 * Copyright 2019 LABOR.digital
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Last modified: 2019.03.22 at 17:34
 */

namespace LaborDigital\T3SAI\Indexer\Transformer;


use LaborDigital\T3SAI\Indexer\IndexerContext;
use LaborDigital\T3SAI\Indexer\IndexNode;

interface RecordTransformerInterface
{
    
    /**
     * This method should be used to create a list of elements (presumably an iterator) for the given language
     * All elements returned will then be passed to the convert() method, one by one, creating a node for every one
     * of them.
     *
     * @param   \LaborDigital\T3SAI\Indexer\IndexerContext  $context
     *
     * @return iterable
     */
    public function resolve(IndexerContext $context): iterable;
    
    /**
     * Receives a single element of the list of resolved elements (generated by resolve()) and should
     * use the raw data to fill the given $node with the required information.
     *
     * @param   mixed                                       $element
     * @param   \LaborDigital\T3SAI\Indexer\IndexNode       $node
     * @param   \LaborDigital\T3SAI\Indexer\IndexerContext  $context
     */
    public function convert($element, IndexNode $node, IndexerContext $context): void;
}
